#!/usr/bin/bash
INDEX=$(pacmd list-cards | awk '/index:/ {a = $2}; /dqbose/ {b = a}; END {print b}')
[ -z "$INDEX" ] && exit 1
SKYPE_INDEX=$(pacmd list-source-outputs | awk '/index:/ {a = $2}; /Skype/ {b = a}; END {print b}')

if [ -n "$(pacmd list-cards | grep 'active profile: <a2dp_sink>')" ]; then
    pacmd set-card-profile $INDEX headset_head_unit
    [ -n "$SKYPE_INDEX" ] && pacmd set-source-output-mute $SKYPE_INDEX 0
else
    pacmd set-card-profile $INDEX a2dp_sink
    [ -n "$SKYPE_INDEX" ] && pacmd set-source-output-mute $SKYPE_INDEX 1
fi
