#!/usr/bin/bash

feh --version > /dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
    exit
fi

arg="--auto-rotate --scale-down"

if [[ $# -eq 0 ]]; then
    feh $arg ./
elif [[ $# -eq 1 ]]; then
    feh $arg --start-at $1
else
    feh $arg $@
fi
