#!/usr/bin/bash

feh --version > /dev/null 2>&1
if [[ ! $? -eq 0 ]]; then
    exit
fi

if [[ $# -eq 0 ]]; then
    feh --auto-rotate --borderless --scale-down ./
elif [[ $# -eq 1 ]]; then
    feh --auto-rotate --borderless --scale-down --start-at $1
else
    feh --auto-rotate --borderless --scale-down $@
fi
