#!/usr/bin/bash
SESSION_NAME=norm

# Exit if session already exists
tmux has-session -t $SESSION_NAME && echo "Tmux session '$SESSION_NAME' already exists!"
tmux has-session -t $SESSION_NAME && exit

tmux new-session -d -s $SESSION_NAME -n 'notes' -c "/media/mikeX/Nextcloud/Notes"
tmux new-window -d -n 'dot' -c $HOME/src/dotfiles
tmux -2 attach-session -t $SESSION_NAME
