#!/usr/bin/bash
HOST_NAME="$(cat /proc/sys/kernel/hostname)"
export HOST_NAME
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export MANWIDTH=80
export LESS=R # This makes less to interpret ANSI color codes.
# make man page colourful
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/bin:$PATH"
export PATH

# Add GPG key
# https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
GPG_TTY="$(tty)"
export GPG_TTY

if [[ (-n "$(command -v ledger)" || -n "$(command -v hledger)") ]]; then
	export LEDGER_FILE=/media/mikeX/Nextcloud/Documents/Ledger/journal.ledger
	export LEDGER_PEDANTIC=1
fi

if [[ $HOST_NAME == 'dq-x1c' && -z $TERM_PROGRAM ]]; then
	export TERM_PROGRAM=gnome-terminal
fi

if [ -x /usr/bin/vim ]; then
	export EDITOR='vim'
	export DIFFPROG='vimdiff'
fi
if [ -x /usr/bin/nvim ]; then
	export EDITOR='nvim'
	#export VISUAL='nvim'
	export DIFFPROG="nvim -d"
fi

export LOADED_BASH_ENV=1

# vi:ft=sh
